window.DEFI_PAGES = {
  features: {
    title: "Features",
    description: "DefiShares official feature overview.",
    visualTitle: "Network Features",
    visualSubtitle: "DFS, GOLD, wallet, explorer, and ecosystem tools",
    introLead:
      "DefiShares is organized as an official information and access portal for the network's core functions.",
    intro:
      "The feature set is presented in the same institutional structure across the site so users can move from project overview to wallet access, explorer lookup, documents, and airdrop information without changing context.",
    bullets: [
      "DFS core asset and DFS address prefix for chain identity;",
      "GOLD-centered policy for DefiShares-managed smart assets;",
      "official Web Wallet access for account and transfer workflows;",
      "public explorer lookup for blocks, transactions, accounts, and assets;",
      "documented project notices, policy references, and airdrop status."
    ],
    directoryTitle: "Feature Areas",
    directory: [
      ["DFS Core Asset", "Network symbol, address prefix, fees, transfers, and market identity."],
      ["GOLD Model", "Protocol-level feed route and collateral policy for managed smart assets."],
      ["Wallet Access", "Official local-signing wallet entry for users."],
      ["Explorer Records", "Public verification for chain activity and distribution records."],
      ["Airdrop Notices", "Allocation, eligibility, snapshot, and claim status once finalized."],
      ["Documents", "Official publications, policy notes, and project references."]
    ],
    operationsTitle: "Current Feature Status",
    operations:
      "The public website presents features according to the confirmed network status. Any feature still pending final operational input should remain labeled as pending or rules pending rather than being presented as live.",
    facts: [
      ["Network", "networkStatus"],
      ["Core asset", "coreAsset"],
      ["Default market", "defaultMarket"],
      ["Block interval", "blockInterval"]
    ]
  },
  gold: {
    title: "GOLD Model",
    description: "DefiShares GOLD-centered feed and smart asset policy.",
    visualTitle: "GOLD Policy",
    visualSubtitle: "Protocol pricing anchor for managed smart assets",
    introLead:
      "DefiShares uses GOLD as the protocol feed anchor for managed DFS-backed smart assets.",
    intro:
      "Witnesses publish TARGET/GOLD for non-GOLD managed bitassets, while chain logic derives the effective TARGET/DFS current feed. This page explains the public-facing policy structure without turning the mechanism into an investment claim.",
    bullets: [
      "GOLD is the routing asset for DefiShares-managed bitassets;",
      "GOLD/DFS pricing is generated by chain policy rather than ordinary witness direct publication;",
      "non-GOLD managed assets publish TARGET/GOLD source feeds;",
      "effective TARGET/DFS is derived by the chain and consumed as current_feed;",
      "managed bitassets use fixed initial collateral ratio policy."
    ],
    directoryTitle: "Policy References",
    directory: [
      ["Feed Anchor", "GOLD is the common route for managed smart asset pricing."],
      ["TARGET/GOLD", "Witness source format for non-GOLD managed DFS-backed assets."],
      ["TARGET/DFS", "Effective feed derived by chain logic for debt and collateral behavior."],
      ["Collateral Policy", "Fixed ICR policy for DefiShares-managed smart assets."],
      ["Risk Limits", "Settlement and liquidation rules differ from upstream behavior."],
      ["Technical Document", "See DefiShares Smartcoin Feed and Risk Policy for implementation details."]
    ],
    operationsTitle: "Important Public Statement",
    operations:
      "GOLD should be described as a protocol policy anchor unless the project has a separate legally verified redemption or reserve program. The website should not imply physical-gold redemption without formal support.",
    facts: [
      ["Core asset", "coreAsset"],
      ["Default market", "defaultMarket"],
      ["Public RPC", "rpcUrl"],
      ["Network", "networkStatus"]
    ]
  },
  wallet: {
    title: "Wallet",
    description: "Official DefiShares wallet access page.",
    visualTitle: "Web Wallet",
    visualSubtitle: "Official local-signing access point",
    introLead:
      "The DefiShares Web Wallet is the official user entry for account access and asset operations.",
    intro:
      "The wallet page is structured as an official access page: users should be able to identify the correct wallet link, understand the local-signing security model, and move to explorer verification after completing transactions.",
    bullets: [
      "create or import a wallet using the official wallet entry;",
      "review DFS and supported asset balances;",
      "transfer and receive assets;",
      "sign transactions locally before broadcast;",
      "verify transaction status through the explorer."
    ],
    directoryTitle: "Wallet Functions",
    directory: [
      ["Open Wallet", "Launch the confirmed Web Wallet URL."],
      ["Account Access", "Create, import, unlock, and manage wallet accounts."],
      ["Transfers", "Send and receive DFS and supported assets."],
      ["Market Access", "Review the default GOLD_DFS market and related assets."],
      ["Local Security", "Private keys and seed phrases should never be submitted to websites."],
      ["Explorer Verification", "Confirm transaction status using the public explorer."]
    ],
    operationsTitle: "Security Reminder",
    operations:
      "The official website should never ask users to enter private keys, seed phrases, or wallet passwords. Wallet access must use the confirmed wallet URL only.",
    facts: [
      ["Wallet URL", "walletUrl"],
      ["Address prefix", "addressPrefix"],
      ["Core asset", "coreAsset"],
      ["Explorer", "explorerUrl"]
    ]
  },
  explorer: {
    title: "Explorer",
    description: "Official DefiShares blockchain explorer page.",
    visualTitle: "Chain Explorer",
    visualSubtitle: "Public chain records and lookup",
    introLead:
      "The DefiShares Explorer is the official public lookup surface for chain activity.",
    intro:
      "A Federal Reserve-style information page should describe what can be verified and where users should go for authoritative records. The explorer is the place for block, transaction, account, asset, and distribution-record review.",
    bullets: [
      "look up latest blocks and block details;",
      "inspect transactions and operation types;",
      "review account balances and activity;",
      "check issued assets, supply data, and market records;",
      "verify airdrop or distribution transactions when published."
    ],
    directoryTitle: "Explorer Records",
    directory: [
      ["Blocks", "Height, timestamp, witness, and included operations."],
      ["Transactions", "Transaction IDs, operation details, fees, and confirmations."],
      ["Accounts", "Balances, permissions, and transaction history."],
      ["Assets", "Supply, issuer, precision, and market-issued asset status."],
      ["Markets", "Trading pairs, order activity, and market references."],
      ["Distributions", "Airdrop and allocation records when published."]
    ],
    operationsTitle: "Record Verification",
    operations:
      "Users should use the confirmed explorer URL from this website to verify transactions and public distribution records. Screenshots or community posts are not a substitute for chain records.",
    facts: [
      ["Explorer URL", "explorerUrl"],
      ["Network", "networkStatus"],
      ["Core asset", "coreAsset"],
      ["Block interval", "blockInterval"]
    ]
  },
  airdrop: {
    title: "Airdrop",
    description: "DefiShares airdrop information page.",
    visualTitle: "DFS Airdrop",
    visualSubtitle: "Rules, eligibility, claims, and public records",
    introLead:
      "The DefiShares airdrop page will publish official distribution rules when finalized.",
    intro:
      "This page follows the same official notice structure: allocation, eligibility, snapshot time, claim window, distribution account, and chain-verifiable records should be presented clearly before any claim flow is promoted.",
    bullets: [
      "state the total allocation and eligible participant groups;",
      "publish snapshot time and qualification rules;",
      "show claim start and end times;",
      "identify whether distribution is one-time or released in batches;",
      "link to distribution records or audit records when available."
    ],
    directoryTitle: "Airdrop Information",
    directory: [
      ["Allocation", "Total airdrop amount and relationship to DFS supply."],
      ["Eligibility", "Account, holder, community, or ecosystem qualification rules."],
      ["Snapshot", "Snapshot time and scope used to determine eligibility."],
      ["Claim Window", "Start time, end time, and claim status."],
      ["Distribution Account", "Official account used for distribution."],
      ["Records", "Explorer links, batch records, and audit summaries."]
    ],
    operationsTitle: "Claim Safety",
    operations:
      "Airdrop pages must not ask for private keys, seed phrases, or wallet passwords. The official site should publish rules before users interact with any claim flow.",
    facts: [
      ["Airdrop status", "airdropStatus"],
      ["Network", "networkStatus"],
      ["Explorer", "explorerUrl"],
      ["Updated", "lastUpdated"]
    ]
  },
  developers: {
    title: "Developers",
    description: "DefiShares developer and node reference page.",
    visualTitle: "Developer Resources",
    visualSubtitle: "RPC, nodes, documents, and repository references",
    introLead:
      "The Developers page provides official technical entry points for DefiShares integrations.",
    intro:
      "The page is intentionally structured like an institutional reference page: it identifies stable public endpoints, implementation documents, and repository links without mixing them with promotional content.",
    bullets: [
      "connect to the public WebSocket RPC endpoint;",
      "review node and chain documentation before deployment;",
      "read the GOLD feed and risk policy document;",
      "verify source code and releases from the confirmed repository;",
      "use explorer records to inspect chain behavior."
    ],
    directoryTitle: "Developer References",
    directory: [
      ["Public RPC", "Official WebSocket endpoint for chain access."],
      ["Core Repository", "Confirmed project source-code repository."],
      ["Node Software", "Witness node and CLI wallet references."],
      ["Wallet UI", "DefiShares UI fork and browser wallet configuration."],
      ["Policy Docs", "Smartcoin feed and risk policy documentation."],
      ["Explorer", "Public record inspection for development and testing."]
    ],
    operationsTitle: "Implementation Notes",
    operations:
      "Technical documents should identify whether references apply to mainnet, testnet, local development, or planned future deployment. Public links should remain versioned and verifiable.",
    facts: [
      ["RPC endpoint", "rpcUrl"],
      ["GitHub", "githubUrl"],
      ["Technical email", "devEmail"],
      ["Network", "networkStatus"],
      ["Block interval", "blockInterval"]
    ]
  },
  documents: {
    title: "Documents",
    description: "DefiShares documents, publications, and notices.",
    visualTitle: "Publications",
    visualSubtitle: "Official documents and risk notices",
    introLead:
      "The Documents page is the official publication index for DefiShares.",
    intro:
      "Following the Federal Reserve-style structure, documents are grouped by purpose: project planning, technical policy, website completion checklists, and risk or disclaimer materials.",
    bullets: [
      "publish project website planning references;",
      "link technical policy documents for GOLD and smart assets;",
      "maintain checklists for remaining content inputs;",
      "include risk notices and user safety statements;",
      "identify update dates for public-facing documents."
    ],
    directoryTitle: "Publication Index",
    directory: [
      ["Website Planning", "Project website sections and content architecture."],
      ["GOLD Feed Policy", "Smartcoin feed and risk policy implementation notes."],
      ["Content Checklist", "Manual content inputs still required from the project team."],
      ["Risk Notice", "User safety, market risk, and disclaimer language."],
      ["Repository", "Source-code and project reference links."],
      ["Updates", "Last updated date and publication status."]
    ],
    operationsTitle: "Document Control",
    operations:
      "Every public document should have a clear owner, version date, and publication status. Unconfirmed claims should remain out of the official document set.",
    facts: [
      ["Documents", "docsUrl"],
      ["GitHub", "githubUrl"],
      ["Contact", "contactEmail"],
      ["Updated", "lastUpdated"],
      ["Risk notice", "riskUrl"]
    ]
  }
};
