window.DEFI_SITE_CONFIG = {
  websiteUrl: "https://defishares.org",
  walletUrl: "https://wallet.defishares.org",
  explorerUrl: "https://explorer.defishares.org",
  githubUrl: "https://github.com/defishares",
  contactEmail: "contact@defishares.org",
  devEmail: "dev@defishares.org",
  docsUrl: "../DefiShares项目官网板块与内容规划.md",
  whitepaperUrl: "#documents",
  riskUrl: "#risk",
  networkStatus: "Public Testnet",
  rpcUrl: "wss://api.defishares.org/ws/",
  coreAsset: "DFS",
  addressPrefix: "DFS",
  defaultMarket: "GOLD_DFS",
  blockInterval: "3 seconds",
  airdropStatus: "Rules pending",
  airdropApiUrl: "/api/v1/airdrop/eligibility",
  airdropChallengeUrl: "/api/v1/airdrop/challenge",
  airdropVerifyUrl: "/api/v1/airdrop/verify",
  lastUpdated: "2026-07-26",
  defaultLanguage: "en",
  supportedLanguages: ["en", "zh"]
};
