window.DEFI_SITE_CONFIG = {
  websiteUrl: "https://defishares.org",
  walletUrl: "https://wallet.defishares.org",
  explorerUrl: "https://explorer.defishares.org",
  githubUrl: "https://github.com/defishares",
  contactEmail: "contact@defishares.org",
  devEmail: "dev@defishares.org",
  docsUrl: "../DefiShares项目官网板块与内容规划.md",
  whitepaperUrl: "#documents",
  riskUrl: "#risk",
  networkStatus: "Mainnet Open",
  chainId: "7089639ad55d91ef53946f3fc4dc86ea5b8a4917edcfce6d3c39bc259657acb5",
  rpcUrl: "wss://api.defishares.org/ws/",
  coreAsset: "DFS",
  addressPrefix: "DFS",
  defaultMarket: "GOLD_DFS",
  blockInterval: "3 seconds",
  airdropStatus: "Rules pending",
  airdropApiUrl: "https://api.defishares.org/airdrop/api/v1/airdrop/eligibility",
  airdropChallengeUrl: "https://api.defishares.org/airdrop/api/v1/airdrop/challenge",
  airdropVerifyUrl: "https://api.defishares.org/airdrop/api/v1/airdrop/verify",
  lastUpdated: "2026-08-15",
  defaultLanguage: "en",
  supportedLanguages: ["en", "zh"]
};
